apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              serviceName: auth-clusterip-srv
              servicePort: 3001
          - path: /api/tickets/?(.*)
            pathType: Prefix
            backend:
              serviceName: tickets-clusterip-srv
              servicePort: 3002
          - path: /api/orders/?(.*)
            pathType: Prefix
            backend:
              serviceName: orders-clusterip-srv
              servicePort: 3003
          - path: /api/payments/?(.*)
            pathType: Prefix
            backend:
              serviceName: payments-clusterip-srv
              servicePort: 3004
          - path: /?(.*)
            pathType: Prefix
            backend:
              serviceName: client-clusterip-srv
              servicePort: 3000

